### ISSUE TITLE
Not working for certain emojis

### ISSUE THREAD

**Issue by Pikachews** [MattFor/emoji-mixer#1]
I'm trying to mix the 🔑 emoji, but it does not appear to work.

The emoji is represented as `1f5dd-fe0f` which does appear in the list of supported emojis (i.e. `index.js`), however when it goes through `toUnicode` the regex does not pass.

If I try to pass the emoji directly into `checkSupported`, it strips the `-fe0f` part, and `1f5dd` is not present in the aforementioned list.

**Comment by MattFor** [comment]
> I'm trying to mix the 🔑 emoji, but it does not appear to work.
> 
> The emoji is represented as `1f5dd-fe0f` which does appear in the list of supported emojis (i.e. `index.js`), however when it goes through `toUnicode` the regex does not pass.
> 
> If I try to pass the emoji directly into `checkSupported`, it strips the `-fe0f` part, and `1f5dd` is not present in the aforementioned list.

Hello! Just released a new version with an improved RegEx for checking supported emojis. 
Hopefully it works for you, send a message here whether it does and I'll close this issue.

**Comment by MattFor** [comment]
Just learned that your particular use case is actually an outdated way of displaying the key emoji.
The program automatically stripped it as it was unneeded for the newest versions. 

This search quickly shows there are 2 versions of "key", you tried to use the older one:
https://emojipedia.org/search?q=key

I've added a parameter oldToNew in some of the functions that automatically should correct some mistakes and hopefully make your experience easier.

**Comment by MattFor** [comment]
Since you aren't responding I'll close the issue. 

Raise another issue if the problem still persists.
